function [price, meta] = c5_market_price_profile(kind, hours)
%C5_MARKET_PRICE_PROFILE Public-market proxy price vectors for C5 runs.
%
% Values are market anchors and policy/projection proxies, not project
% contracts. They are suitable for scenario analysis and sensitivity runs.

if nargin < 2 || isempty(hours)
    hours = 8760;
end

anchors = struct( ...
    'electricityAnnualAverageCNYPerMWh', 401.34, ...
    'electricityHighMonthCNYPerMWh', 401.34, ...
    'greenElectricityPremiumCNYPerMWh', 47.00, ...
    'hydrogenGreenIndexCNYPerKg', 28.36, ...
    'computeBlendedCNYPerMWhIT', 5000.00, ...
    'computeLowCNYPerMWhIT', 2180.39, ...
    'computeFlexibleBatchCNYPerMWhIT', 3905.88, ...
    'computeRigidInferenceCNYPerMWhIT', 5945.10, ...
    'computeHighCNYPerMWhIT', 6964.71);

price = zeros(hours, 1);
switch char(kind)
    case 'electricity_annual_base'
        price(:) = anchors.electricityAnnualAverageCNYPerMWh;
        scenarioId = 'GD_2026_ANNUAL_AVERAGE';
    case 'electricity_48h_mechanism'
        price(hour_range(13, 18, hours)) = ...
            anchors.electricityAnnualAverageCNYPerMWh;
        price(hour_range(19, 36, hours)) = ...
            anchors.electricityHighMonthCNYPerMWh + ...
            anchors.greenElectricityPremiumCNYPerMWh;
        price(hour_range(37, 40, hours)) = ...
            anchors.electricityHighMonthCNYPerMWh;
        scenarioId = 'GD_2026_MARKET_WINDOW_WITH_GREEN_PREMIUM';
    case 'hydrogen_annual_base'
        price(:) = anchors.hydrogenGreenIndexCNYPerKg;
        scenarioId = 'GREEN_H2_MARKET_INDEX_BASE';
    case 'hydrogen_48h_mechanism'
        price(hour_range(25, 36, hours)) = ...
            anchors.hydrogenGreenIndexCNYPerKg;
        scenarioId = 'GREEN_H2_MARKET_INDEX_WINDOW';
    case 'compute_annual_base'
        price(:) = anchors.computeBlendedCNYPerMWhIT;
        scenarioId = 'PUBLIC_GPU_RENTAL_BLENDED_PROXY';
    case 'compute_48h_mechanism'
        price(hour_range(13, 36, hours)) = ...
            anchors.computeRigidInferenceCNYPerMWhIT;
        price(hour_range(37, 40, hours)) = ...
            anchors.computeLowCNYPerMWhIT;
        scenarioId = 'PUBLIC_GPU_RENTAL_SERVICE_WINDOWS';
    otherwise
        error('Unknown C5 market price profile: %s', char(kind));
end

meta = struct( ...
    'scenarioId', scenarioId, ...
    'anchors', anchors, ...
    'sourceStatus', ...
        ['PUBLIC_MARKET_PROXY_NOT_PROJECT_CONTRACT; ', ...
         '[假设值，待企业调研校准]']);
end

function r = hour_range(firstHour, lastHour, horizonHours)
r = firstHour:min(lastHour, horizonHours);
end
